### ISSUE TITLE
CSS library discussion

### ISSUE THREAD

**Issue by hoatran1403** [meerkats-sundial/sundial-frontend#4]
Hi guys @nionata @ejuor ,
Currently I see we use different css libraries for landing page(**skeleton.css**) and meeting schedule page(**bootstrap**). Since, There are some reusable UI components like header, footer or navbar (if any) so I think we should pick 1 between them then we can reuse the common components. What do you guys think? And I'm also not sure which one is better for our project

**Comment by ejuor** [comment]
I'm also not sure which is better 😄.

**Comment by nionata** [comment]
Yes I think it will be good to pick just one to use. Maybe tonight at our meeting we can take a second to discuss it?
